name: Dawsino
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
title: Dawsino
email: dawsneyland@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write a brilliant description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.dawsneyland.com" # the base hostname & protocol for your site
twitter_username: dawsneyland
github_username:  dawsneyland
instagram_username: dawsneyland
pinterest_username: dawsneyland
