# Site settings
title: MartsVideoClub
header-img: img/bench.jpg
email: martsvideoclub@gmail.com
copyright_name: Martin Dawson
description: "Videos, photos and words about my family."
baseurl: ""
#url: "http://www.dawsneyland.com"
#twitter_username: dawsneyland
#instagram_username:  dawsneyland
#youtube_username:  dawsneyland
#pinterest_username:  dawsneyland
#disqusid: disqus_5CGZhxZvQy

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","projects","contact"]

gems: [jekyll-paginate, jekyll-feed]
